"""initial schema — all account + visual models

Recreates the full schema from data_viz/database/models.py in foreign-key
dependency order. This replaces the previous migration chain, which was
autogenerated against a database where the users/groups/user_groups tables
already existed and therefore never created them (nor invite_groups), leaving
a fresh `flask db upgrade` unable to build the schema.

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-06-16

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001_initial_schema'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('username', sa.String(length=255), nullable=False),
        sa.Column('password_hash', sa.String(length=255), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=True),
        sa.Column('site_admin', sa.Boolean(), nullable=True),
        sa.Column('invited_by', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('username'),
    )

    op.create_table(
        'groups',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.String(length=255), nullable=True),
        sa.Column('created_by', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )

    op.create_table(
        'user_groups',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('group_id', sa.Integer(), nullable=False),
        sa.Column('role', sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'group_id', name='uq_user_group'),
    )

    op.create_table(
        'invites',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('token', sa.String(length=512), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=True),
        sa.Column('sent_at', sa.DateTime(), nullable=False),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.Column('expiry_task_id', sa.String(length=255), nullable=True),
        sa.Column('sent_by', sa.Integer(), nullable=False),
        sa.Column('site_admin_invite', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['sent_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )

    op.create_table(
        'invite_groups',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('invite_id', sa.Integer(), nullable=False),
        sa.Column('group_id', sa.Integer(), nullable=False),
        sa.Column('role', sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
        sa.ForeignKeyConstraint(['invite_id'], ['invites.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )

    op.create_table(
        'visuals',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('about', sa.String(length=5000), nullable=True),
        sa.Column('province', sa.String(length=255), nullable=False),
        sa.Column('vis_type', sa.String(length=255), nullable=False),
        sa.Column('data_types', sa.String(length=255), nullable=False),
        sa.Column('menu_name', sa.String(length=255), nullable=False),
        sa.Column('menu_parent', sa.String(length=255), nullable=False),
        sa.Column('level', sa.String(length=255), nullable=False),
        sa.Column('next_vis', sa.Integer(), nullable=True),
        sa.Column('previous_vis', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['next_vis'], ['visuals.id'], ),
        sa.ForeignKeyConstraint(['previous_vis'], ['visuals.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )

    op.create_table(
        'group_visuals',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('group_id', sa.Integer(), nullable=False),
        sa.Column('visual_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
        sa.ForeignKeyConstraint(['visual_id'], ['visuals.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )

    op.create_table(
        'data_sources',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('link', sa.String(length=255), nullable=False),
        sa.Column('last_updated', sa.DateTime(), nullable=False),
        sa.Column('data_until', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )

    op.create_table(
        'data_points',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('data_source_id', sa.Integer(), nullable=False),
        sa.Column('geo_type', sa.String(length=255), nullable=False),
        sa.Column('geo', sa.String(length=255), nullable=False),
        sa.Column('time_frame_type', sa.String(length=255), nullable=False),
        sa.Column('time_frame', sa.String(length=255), nullable=False),
        sa.Column('data_metric', sa.String(length=255), nullable=False),
        sa.Column('data_value', sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('data_points', schema=None) as batch_op:
        batch_op.create_index(
            'idx_datapoints_visual_geo_year',
            ['geo', 'time_frame_type', 'data_metric'],
            unique=False,
        )

    op.create_table(
        'visual_queries',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('filter_type', sa.String(length=255), nullable=False),
        sa.Column('filter_value', sa.String(length=255), nullable=False),
        sa.Column('for_visual_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['for_visual_id'], ['visuals.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )

    op.create_table(
        'user_activity',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('activity_type', sa.String(length=255), nullable=False),
        sa.Column('activity_target_type', sa.String(length=255), nullable=True),
        sa.Column('activity_target_id', sa.Integer(), nullable=True),
        sa.Column('details', sa.String(length=5000), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.Column('ip_address', sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )


def downgrade():
    op.drop_table('user_activity')
    op.drop_table('visual_queries')
    with op.batch_alter_table('data_points', schema=None) as batch_op:
        batch_op.drop_index('idx_datapoints_visual_geo_year')
    op.drop_table('data_points')
    op.drop_table('data_sources')
    op.drop_table('group_visuals')
    op.drop_table('visuals')
    op.drop_table('invite_groups')
    op.drop_table('invites')
    op.drop_table('user_groups')
    op.drop_table('groups')
    op.drop_table('users')
