"""add group_data_sources and relax data_sources nullability

Revision ID: 248d9a2cdf2e
Revises: 0001_initial_schema
Create Date: 2026-06-16 21:27:06.227883

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '248d9a2cdf2e'
down_revision = '0001_initial_schema'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'data_source_id', name='uq_group_data_source')
    )
    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.alter_column('link',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('last_updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('data_until',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.alter_column('data_until',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('last_updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('link',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    op.drop_table('group_data_sources')
    # ### end Alembic commands ###
