"""drop dead visuals.next_vis/previous_vis FK columns

Revision ID: 3650cbbadd03
Revises: 50cae918586a
Create Date: 2026-06-18 05:20:08.066424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3650cbbadd03'
down_revision = '50cae918586a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visuals', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('visuals_next_vis_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('visuals_previous_vis_fkey'), type_='foreignkey')
        batch_op.drop_column('previous_vis')
        batch_op.drop_column('next_vis')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visuals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_vis', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('previous_vis', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('visuals_previous_vis_fkey'), 'visuals', ['previous_vis'], ['id'])
        batch_op.create_foreign_key(batch_op.f('visuals_next_vis_fkey'), 'visuals', ['next_vis'], ['id'])

    # ### end Alembic commands ###
