"""add visuals.substance

Revision ID: 50cae918586a
Revises: cfd4942710c2
Create Date: 2026-06-18 04:35:56.322987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50cae918586a'
down_revision = 'cfd4942710c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visuals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('substance', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visuals', schema=None) as batch_op:
        batch_op.drop_column('substance')

    # ### end Alembic commands ###
