"""add menu/presentation columns to visuals (stage 1)

Revision ID: 53280e8f501e
Revises: 7e72cf29af2e
Create Date: 2026-06-17 14:59:19.256226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53280e8f501e'
down_revision = '7e72cf29af2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visuals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chart_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('next_vis_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('vis_parent_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_default', sa.Boolean(), nullable=True))
        batch_op.alter_column('data_types',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visuals', schema=None) as batch_op:
        batch_op.alter_column('data_types',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('is_default')
        batch_op.drop_column('vis_parent_name')
        batch_op.drop_column('next_vis_name')
        batch_op.drop_column('chart_type')

    # ### end Alembic commands ###
