"""add token and expiry_task_id to invites

Revision ID: 5b1db9aebf93
Revises: edba7cb3d7b8
Create Date: 2026-05-12 20:49:49.891353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b1db9aebf93'
down_revision = 'edba7cb3d7b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expiry_task_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.drop_column('expiry_task_id')

    # ### end Alembic commands ###
