"""das explorer tables

Revision ID: 7a0ca3695419
Revises: a7f3c1b9d2e4
Create Date: 2026-08-04 16:55:36.170200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a0ca3695419'
down_revision = 'a7f3c1b9d2e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('das_drug_codes',
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('english_name', sa.String(length=500), nullable=True),
    sa.Column('french_name', sa.String(length=500), nullable=True),
    sa.Column('english_legal_name', sa.String(length=500), nullable=True),
    sa.Column('french_legal_name', sa.String(length=500), nullable=True),
    sa.Column('pharm_class', sa.String(length=255), nullable=True),
    sa.Column('pharm_subclass', sa.String(length=255), nullable=True),
    sa.Column('cas', sa.String(length=255), nullable=True),
    sa.Column('act', sa.String(length=255), nullable=True),
    sa.Column('schedule', sa.String(length=255), nullable=True),
    sa.Column('item', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('das_samples',
    sa.Column('sample_number', sa.String(length=255), nullable=False),
    sa.Column('public_health', sa.Boolean(), nullable=True),
    sa.Column('contains_nps', sa.Boolean(), nullable=True),
    sa.Column('date_received', sa.Date(), nullable=True),
    sa.Column('date_returned', sa.Date(), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('province', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('drugs_identified', sa.Text(), nullable=True),
    sa.Column('source_month', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('sample_number')
    )
    with op.batch_alter_table('das_samples', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_das_samples_date_received'), ['date_received'], unique=False)
        batch_op.create_index(batch_op.f('ix_das_samples_date_returned'), ['date_returned'], unique=False)
        batch_op.create_index(batch_op.f('ix_das_samples_province'), ['province'], unique=False)
        batch_op.create_index(batch_op.f('ix_das_samples_source_month'), ['source_month'], unique=False)

    op.create_table('das_nps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_number', sa.String(length=255), nullable=False),
    sa.Column('drug_code', sa.String(length=255), nullable=True),
    sa.Column('substance_name', sa.String(length=500), nullable=True),
    sa.Column('other_name', sa.Text(), nullable=True),
    sa.Column('province', sa.String(length=50), nullable=True),
    sa.Column('finding_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_month', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['drug_code'], ['das_drug_codes.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('das_nps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_das_nps_province'), ['province'], unique=False)
        batch_op.create_index(batch_op.f('ix_das_nps_sample_number'), ['sample_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_das_nps_source_month'), ['source_month'], unique=False)

    op.create_table('das_quant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_number', sa.String(length=255), nullable=False),
    sa.Column('public_health', sa.Boolean(), nullable=True),
    sa.Column('date_received', sa.Date(), nullable=True),
    sa.Column('date_returned', sa.Date(), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('province', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('drug_code', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('units', sa.String(length=50), nullable=True),
    sa.Column('source_month', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['drug_code'], ['das_drug_codes.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('das_quant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_das_quant_province'), ['province'], unique=False)
        batch_op.create_index(batch_op.f('ix_das_quant_sample_number'), ['sample_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_das_quant_source_month'), ['source_month'], unique=False)

    op.create_table('das_sample_drugs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_number', sa.String(length=255), nullable=False),
    sa.Column('drug_code', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['drug_code'], ['das_drug_codes.code'], ),
    sa.ForeignKeyConstraint(['sample_number'], ['das_samples.sample_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sample_number', 'position', name='uq_das_sample_drug_position')
    )
    with op.batch_alter_table('das_sample_drugs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_das_sample_drugs_drug_code'), ['drug_code'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('das_sample_drugs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_das_sample_drugs_drug_code'))

    op.drop_table('das_sample_drugs')
    with op.batch_alter_table('das_quant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_das_quant_source_month'))
        batch_op.drop_index(batch_op.f('ix_das_quant_sample_number'))
        batch_op.drop_index(batch_op.f('ix_das_quant_province'))

    op.drop_table('das_quant')
    with op.batch_alter_table('das_nps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_das_nps_source_month'))
        batch_op.drop_index(batch_op.f('ix_das_nps_sample_number'))
        batch_op.drop_index(batch_op.f('ix_das_nps_province'))

    op.drop_table('das_nps')
    with op.batch_alter_table('das_samples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_das_samples_source_month'))
        batch_op.drop_index(batch_op.f('ix_das_samples_province'))
        batch_op.drop_index(batch_op.f('ix_das_samples_date_returned'))
        batch_op.drop_index(batch_op.f('ix_das_samples_date_received'))

    op.drop_table('das_samples')
    op.drop_table('das_drug_codes')
    # ### end Alembic commands ###
