"""add data layer columns to visuals, data_sources, data_points

Revision ID: 7e72cf29af2e
Revises: 248d9a2cdf2e
Create Date: 2026-06-17 05:03:23.156599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e72cf29af2e'
down_revision = '248d9a2cdf2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_points', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('dimension_type', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('dimension_value', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('dimension2_type', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('dimension2_value', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('data_value_text', sa.String(length=255), nullable=True))
        batch_op.alter_column('data_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.drop_index(batch_op.f('idx_datapoints_visual_geo_year'))
        batch_op.create_index('idx_datapoints_metric_geo_year', ['data_source_id', 'data_metric', 'geo', 'time_frame'], unique=False)

    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('last_updated_str', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('data_until_str', sa.String(length=255), nullable=True))

    with op.batch_alter_table('visuals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_source_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('visual_options', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('data_shape', sa.String(length=50), nullable=True))
        batch_op.alter_column('menu_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('menu_parent',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('level',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.create_foreign_key(None, 'data_sources', ['data_source_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visuals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('level',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('menu_parent',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('menu_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('data_shape')
        batch_op.drop_column('visual_options')
        batch_op.drop_column('data_source_id')

    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.drop_column('data_until_str')
        batch_op.drop_column('last_updated_str')
        batch_op.drop_column('about')

    with op.batch_alter_table('data_points', schema=None) as batch_op:
        batch_op.drop_index('idx_datapoints_metric_geo_year')
        batch_op.create_index(batch_op.f('idx_datapoints_visual_geo_year'), ['geo', 'time_frame_type', 'data_metric'], unique=False)
        batch_op.alter_column('data_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.drop_column('data_value_text')
        batch_op.drop_column('dimension2_value')
        batch_op.drop_column('dimension2_type')
        batch_op.drop_column('dimension_value')
        batch_op.drop_column('dimension_type')
        batch_op.drop_column('data_type')

    # ### end Alembic commands ###
