"""add sent_at to invites

Revision ID: a3334452c89d
Revises: 5b1db9aebf93
Create Date: 2026-05-12 21:41:55.126714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3334452c89d'
down_revision = '5b1db9aebf93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sent_at', sa.DateTime(), nullable=False, server_default=sa.func.current_timestamp()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.drop_column('sent_at')

    # ### end Alembic commands ###
