"""stage 2c: key_kind column on visuals

Revision ID: cfd4942710c2
Revises: fc1356c850d0
Create Date: 2026-06-17 21:36:57.566545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfd4942710c2'
down_revision = 'fc1356c850d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visuals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key_kind', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visuals', schema=None) as batch_op:
        batch_op.drop_column('key_kind')

    # ### end Alembic commands ###
