"""fleshed out account system and hidden visual db models

Revision ID: edba7cb3d7b8
Revises: 
Create Date: 2026-03-03 15:07:56.011524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edba7cb3d7b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('data_until', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visuals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('about', sa.String(length=5000), nullable=True),
    sa.Column('province', sa.String(length=255), nullable=False),
    sa.Column('vis_type', sa.String(length=255), nullable=False),
    sa.Column('data_types', sa.String(length=255), nullable=False),
    sa.Column('menu_name', sa.String(length=255), nullable=False),
    sa.Column('menu_parent', sa.String(length=255), nullable=False),
    sa.Column('level', sa.String(length=255), nullable=False),
    sa.Column('next_vis', sa.Integer(), nullable=True),
    sa.Column('previous_vis', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['next_vis'], ['visuals.id'], ),
    sa.ForeignKeyConstraint(['previous_vis'], ['visuals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.Column('geo_type', sa.String(length=255), nullable=False),
    sa.Column('geo', sa.String(length=255), nullable=False),
    sa.Column('time_frame_type', sa.String(length=255), nullable=False),
    sa.Column('time_frame', sa.String(length=255), nullable=False),
    sa.Column('data_metric', sa.String(length=255), nullable=False),
    sa.Column('data_value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_points', schema=None) as batch_op:
        batch_op.create_index('idx_datapoints_visual_geo_year', ['geo', 'time_frame_type', 'data_metric'], unique=False)

    op.create_table('user_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('activity_type', sa.String(length=255), nullable=False),
    sa.Column('activity_target_type', sa.String(length=255), nullable=True),
    sa.Column('activity_target_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.String(length=5000), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visual_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filter_type', sa.String(length=255), nullable=False),
    sa.Column('filter_value', sa.String(length=255), nullable=False),
    sa.Column('for_visual_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['for_visual_id'], ['visuals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_visuals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('visual_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['visual_id'], ['visuals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('sent_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['sent_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])

    with op.batch_alter_table('user_groups', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_group', ['user_id', 'group_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('site_admin', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('invited_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['invited_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('invited_by')
        batch_op.drop_column('site_admin')
        batch_op.drop_column('status')

    with op.batch_alter_table('user_groups', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_group', type_='unique')

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_at')
        batch_op.drop_column('created_by')

    op.drop_table('invites')
    op.drop_table('group_visuals')
    op.drop_table('visual_queries')
    op.drop_table('user_activity')
    with op.batch_alter_table('data_points', schema=None) as batch_op:
        batch_op.drop_index('idx_datapoints_visual_geo_year')

    op.drop_table('data_points')
    op.drop_table('visuals')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
