"""stage 2a: self-describing query columns on visuals

Revision ID: fc1356c850d0
Revises: a1b2c3d4e5f6
Create Date: 2026-06-17 21:11:42.058329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc1356c850d0'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visuals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metric', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('geo_type', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('dimension_type', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('dimension2_type', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('drill_chain', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visuals', schema=None) as batch_op:
        batch_op.drop_column('drill_chain')
        batch_op.drop_column('dimension2_type')
        batch_op.drop_column('dimension_type')
        batch_op.drop_column('geo_type')
        batch_op.drop_column('metric')

    # ### end Alembic commands ###
